import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

vi.mock('../utils/mailer.js', () => ({
  verifyConnections: vi.fn(async () => {}),
  sendMail: vi.fn(async () => ({ messageId: '<abc@test.com>' }))
}));
vi.mock('../utils/telegram.js', () => ({ sendAlert: vi.fn(async () => {}) }));
vi.mock('../utils/contentValidator.js', () => ({ validate: vi.fn(() => ({ valid: true })) }));
vi.mock('../utils/sleep.js', () => ({ sleep: vi.fn(async () => {}) }));

let tmpDir;
beforeEach(async () => {
  tmpDir = mkdtempSync(join(tmpdir(), 'radar-test-'));
  process.env.DB_PATH = join(tmpDir, 'radar.sqlite');
  process.env.DAILY_SEND_LIMIT = '10';
  process.env.OUTREACH_DOMAIN = 'trysimpleinc.com';
  process.env.BOUNCE_RATE_HARD_STOP = '0.02';
  process.env.SEND_WINDOW_START_IST = '0';
  process.env.SEND_WINDOW_END_IST = '23';
  process.env.SEND_DELAY_MIN_MS = '1000';
  process.env.SEND_DELAY_MAX_MS = '2000';
  process.env.INBOX_1_USER = 'darshan@trysimpleinc.com';
  process.env.INBOX_2_USER = 'hello@trysimpleinc.com';
  const { resetDb, initSchema, getDb } = await import('../utils/db.js');
  resetDb();
  initSchema();
  // Insert a ready lead with subject and body already generated by findLeads
  getDb().prepare(`
    INSERT INTO leads (company, contact_email, contact_name, icp_priority, icp_score, email_subject, email_body, hook, status)
    VALUES ('Acme', 'john@acme.com', 'John', 'A', 8, 'Quick question', 'Hi John I noticed your website has not been updated in a few years. I help businesses like yours modernize their web presence quickly. Would you be open to a quick chat about this? Reply to this email and we can find a time. Best regards Darshan', 'Your site looks dated.', 'ready')
  `).run();
});

afterEach(async () => {
  const { resetDb } = await import('../utils/db.js');
  resetDb();
  rmSync(tmpDir, { recursive: true });
});

describe('sendEmails', () => {
  it('sends emails to ready leads and updates status', async () => {
    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const { getDb } = await import('../utils/db.js');
    const emails = getDb().prepare(`SELECT * FROM emails WHERE status='sent'`).all();
    expect(emails.length).toBeGreaterThan(0);
    expect(emails[0].message_id).toBe('<abc@test.com>');
    expect(emails[0].sequence_step).toBe(0);
    const lead = getDb().prepare(`SELECT status FROM leads WHERE contact_email='john@acme.com'`).get();
    expect(lead.status).toBe('contacted');
  });

  it('initialises sequence_state after sending', async () => {
    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const { getDb } = await import('../utils/db.js');
    const seq = getDb().prepare(`SELECT * FROM sequence_state`).get();
    expect(seq).toBeTruthy();
    expect(seq.current_step).toBe(0);
    expect(seq.status).toBe('active');
    expect(seq.last_message_id).toBe('<abc@test.com>');
  });

  it('skips when DAILY_SEND_LIMIT is 0', async () => {
    process.env.DAILY_SEND_LIMIT = '0';
    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const { getDb } = await import('../utils/db.js');
    const emails = getDb().prepare(`SELECT * FROM emails`).all();
    expect(emails.length).toBe(0);
  });

  it('skips leads in reject list', async () => {
    const { addToRejectList } = await import('../utils/db.js');
    addToRejectList('john@acme.com', 'unsubscribe');
    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const { getDb } = await import('../utils/db.js');
    const emails = getDb().prepare(`SELECT * FROM emails`).all();
    expect(emails.length).toBe(0);
  });

  it('respects daily send limit', async () => {
    process.env.DAILY_SEND_LIMIT = '1';
    // Insert a second ready lead
    const { getDb } = await import('../utils/db.js');
    getDb().prepare(`
      INSERT INTO leads (company, contact_email, contact_name, icp_priority, icp_score, email_subject, email_body, hook, status)
      VALUES ('Beta', 'jane@beta.com', 'Jane', 'A', 9, 'Your website', 'Hi Jane I noticed your website has not been updated in a few years. I help businesses like yours modernize their web presence quickly. Would you be open to a quick chat about this? Reply to this email and we can find a time. Best regards Darshan', 'Your site looks old.', 'ready')
    `).run();

    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const emails = getDb().prepare(`SELECT * FROM emails WHERE status='sent'`).all();
    expect(emails.length).toBe(1);
  });

  it('round-robins between inboxes', async () => {
    process.env.DAILY_SEND_LIMIT = '10';
    const { getDb } = await import('../utils/db.js');
    getDb().prepare(`
      INSERT INTO leads (company, contact_email, contact_name, icp_priority, icp_score, email_subject, email_body, hook, status)
      VALUES ('Beta', 'jane@beta.com', 'Jane', 'B', 7, 'Your website', 'Hi Jane I noticed your website has not been updated in a few years. I help businesses like yours modernize their web presence quickly. Would you be open to a quick chat about this? Reply to this email and we can find a time. Best regards Darshan', 'Your site looks old.', 'ready')
    `).run();

    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const emails = getDb().prepare(`SELECT * FROM emails ORDER BY id`).all();
    expect(emails.length).toBe(2);
    // Should use different inboxes
    expect(emails[0].inbox).not.toBe(emails[1].inbox);
  });

  it('logs to cron_log', async () => {
    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const { getDb } = await import('../utils/db.js');
    const cronEntries = getDb().prepare(`SELECT * FROM cron_log WHERE job_name='sendEmails'`).all();
    expect(cronEntries.length).toBe(1);
    expect(cronEntries[0].status).toBe('ok');
    expect(cronEntries[0].emails_sent).toBe(1);
  });

  it('bumps daily_metrics emails_sent', async () => {
    const sendEmails = (await import('../sendEmails.js')).default;
    await sendEmails();
    const { getDb, today } = await import('../utils/db.js');
    const metrics = getDb().prepare(`SELECT * FROM daily_metrics WHERE date=?`).get(today());
    expect(metrics).toBeTruthy();
    expect(metrics.emails_sent).toBe(1);
  });
});
