import { builder } from './builder.js'
import './resolvers/leads.js'
import './resolvers/me.js'
import './resolvers/orgs.js'
import './resolvers/admin.js'
import './resolvers/config.js'
import './resolvers/niches.js'
import './resolvers/offer.js'
import './resolvers/icpProfile.js'
import './resolvers/sequences.js'
import './resolvers/savedViews.js'
import './resolvers/engineGuardrails.js'
import './resolvers/overview.js'
import './resolvers/funnel.js'
import './resolvers/sendLog.js'
import './resolvers/costs.js'
import './resolvers/errors.js'
import './resolvers/cronStatus.js'
import './resolvers/replies.js'

export const schema = builder.toSchema()
